### ISSUE TITLE
The script has not started since the last Ubuntu update.

### ISSUE THREAD

**Issue by unix1984** [yoshtec/snapbtrex#22]
Hello,

The script has not started since the last Ubuntu update.
It has worked perfectly so far. I updated it a few days ago and it has happened ever since.

[11:55:09][root@vmd58232:~]$ /usr/local/sbin/snapbtrex.py --snap / --path /mnt/sda2/autosnap/daily --target-backups 10 --verbose --remote-host 192.168.10.9 --remote-dir /mnt/sdb2/BACKUP/VPS-rootfs/daily --remote-keep 15
Local  > snapshotting path=/ to newdir=/mnt/sda2/autosnap/daily/20220428-115545
EXEC  >-> sudo btrfs subvolume snapshot -r / /mnt/sda2/autosnap/daily/20220428-115545
OUTPUT > Create a readonly snapshot of '/' in '/mnt/sda2/autosnap/daily/20220428-115545'

Local  > sync filesystem /mnt/sda2/autosnap/daily
EXEC  >-> sudo btrfs filesystem sync /mnt/sda2/autosnap/daily
Local  > done sync filesystem /mnt/sda2/autosnap/daily
Local  > done snapshotting
Remote > list remote files host=192.168.10.9, dir=/mnt/sdb2/BACKUP/VPS-rootfs/daily
EXEC  >-> ssh -p 22 192.168.10.9 ls -1 /mnt/sdb2/BACKUP/VPS-rootfs/daily
OUTPUT > 

20220402-234501
20220404-234501
20220406-234502
20220408-234502
20220410-234502
20220412-234501
20220413-234501
20220414-234501
20220415-234501
20220416-234502
20220417-234501
20220418-234501
20220419-234502
20220420-234502
20220421-234501

Traceback (most recent call last):
  File "/usr/local/sbin/snapbtrex.py", line 1072, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/sbin/snapbtrex.py", line 1026, in main
    transfer(
  File "/usr/local/sbin/snapbtrex.py", line 548, in transfer
    targetsnaps = set(operations.listremote_dir(target_host, target_dir, ssh_port))
  File "/usr/local/sbin/snapbtrex.py", line 275, in listremote_dir
    return [
  File "/usr/local/sbin/snapbtrex.py", line 276, in <listcomp>
    d for d in self.check_call(args, dry_safe=True).splitlines() if timef(d)
  File "/usr/local/sbin/snapbtrex.py", line 134, in timef
    v = math.exp(_timestamp(x) / TIME_SCALE)
  File "/usr/local/sbin/snapbtrex.py", line 149, in _timestamp
    return time.mktime(time.strptime(os.path.split(x)[1], DATE_FORMAT))
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y%m%d-%H%M%S'
[11:55:45][root@vmd58232:~]$ 

[11:19:32][root@vmd58232:~]$ python3 --version
Python 3.8.10

Regards!

**Comment by yoshtec** [comment]
It seems that the behaviour of` ls -1` has changed (maybe only while doing it over ssh) and it displays one additional line, which snapbtrex tries to parse as date. But since it is empty parsing fails. 
@unix1984 Can you checkout the pypi branch and check if the error still exists? you also have to change the path by adding one snapbtrex path level at the end.

**Comment by unix1984** [comment]
Hi yoshtec!

It was already enough that the Python update destroys the functionality of the script every six months.
I no longer use the script.
I wrote a BASH script and use it.
https://github.com/unix1984/btrfsback-lite

But thanks!
